name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    # Utilisation d'Ubuntu pour supporter gunicorn et les scripts shell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      
      # Ajout de la configuration Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      # Installation des dépendances Python
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend-traitement/requirements.txt

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        # SonarQube détectera automatiquement les fichiers Python dans backend-traitement

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          # Remplacez les valeurs ci-dessous par celles de votre compte SonarQube
          args: >
            -Dsonar.organization=SONAR_TOKEN
            -Dsonar.projectKey=a45ba6549e356f310a9e64474b00bdf5ba175a73
            -Dsonar.sources=.
            -Dsonar.verbose=true